In [2]:
import numpy as np

In [5]:
a1=np.array([1,2,3,4])
print("example 1",a1)

example 1 [1 2 3 4]


In [7]:
a2 =np.zeros((2,3,4))

In [8]:
print(a2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
a= np.array([[1,2,3],[4,5,6]])

In [13]:
print(f"shape = {a.shape} and size = {a.size} and dim={a.ndim}")

shape = (2, 3) and size = 6 and dim=2


In [17]:
print(f"d type ={a.dtype} itemsize ={a.itemsize} nbyte={a.nbytes}")

d type =int64 itemsize =8 nbyte=48


In [20]:

arr_arrange=np.arange(1,5,0.5)

In [22]:
print(f"arrange {arr_arrange}")

arrange [1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [23]:
print(type(arr_arrange))

<class 'numpy.ndarray'>


In [25]:
arr_lin=np.linspace(0,100,5)

In [27]:
print(arr_lin)

[  0.  25.  50.  75. 100.]


In [29]:
arr=np.arange(10)

In [32]:
print(arr[:10])

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(arr[::3])

[0 3 6 9]


In [39]:
mat = np.arange(1,13).reshape(3,4)

In [40]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
print(mat[0:2,1:3])

[[2 3]
 [6 7]]


In [43]:
a=np.array([10,20,30,40])

In [44]:
v=a[1:3]

In [45]:
v[0]=999

In [46]:
print(a)

[ 10 999  30  40]


In [47]:
arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])

[10 30 50]


In [48]:
print(arr[[1,4]])

[20 50]
